### ISSUE TITLE
1.8.26 null pointer exception

### ISSUE THREAD

**Issue by JrAnTran** [ivk1800/prebuild#1]
@ivk1800 
Please help check:

Configuration:
|---------|:-------------------------------------------------------------:|-----------------------------------------------------------------------------------:|
| 1.8.26  |                          last commit                          |   [b1b33cf](https://github.com/tdlib/td/blob/b1b33cf/td/generate/scheme/td_api.tl) |

Anrdoi prebuillt 1.8.26 :
https://github.com/ivk1800/td-json-client-prebuilt/releases/download/android-1.8.26-b1b33cf/libs.zip

++++++++++++++++++++++++++++++++++++++++
Stacktrace:

#0      Chat.fromJson (package:tdlib/src/api/objects/chat.dart:25
![Screenshot from 2024-05-09 00-13-23](https://github.com/ivk1800/td-json-client-prebuilt/assets/169292674/25843e6c-2935-4a1c-a800-8498490a41a2)
5:79)
#1      UpdateNewChat.fromJson (package:tdlib/src/api/objects/update_new_chat.dart:25:18)
#2      ConvertExtensions.toTdObject (package:tdlib/src/api/extensions/convert_extensions.dart:2910:30)
#3      receiveIsolateEntryPoint (package:tdlib/src/client/platform/io/receive_isolate_endpoint.dart:21:34)
<asynchronous suspension>

**Comment by ivk1800** [comment]
👍🏽 Fixed https://github.com/ivk1800/tdlib-dart/commit/d52eb0540ea3b77a8614300bc8c827335cb8b1af
Please check 1.8.29 version;
