### ISSUE TITLE
a lot of warning when building opeen ssl 3.0.13

### ISSUE THREAD

**Issue by JrAnTran** [ivk1800/prebuild#2]
@ivk1800 

Hello, 

I'm compiling libtdjsonandroid with your fix on 1.8.29, using instructions here https://github.com/tdlib/td/issues/77#issuecomment-640719893

open-ssl 3.0.13
and ndk version 23.2.8568313

it then generates  a lot of warnings on building process, any way at the end it produces 4 folders including (see the picture attached) with libs created inside.

Is that an issue?
![Screenshot from 2024-05-09 11-00-49](https://github.com/ivk1800/td-json-client-prebuilt/assets/169292674/3c390db9-2d03-4be0-b614-b1f9e5b4a2aa)

+++++++++++++++++++++++++++++++++++++++++++++++
 warning generated.
In file included from <built-in>:368:
<command line>:3:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 21
        ^
<built-in>:361:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
1 warning generated.
In file included from <built-in>:368:
<command line>:3:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 21
        ^
<built-in>:361:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
1 warning generated.
In file included from <built-in>:368:
<command line>:3:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 21
        ^
<built-in>:361:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
1 warning generated.
In file included from <built-in>:368:
<command line>:3:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 21
        ^
<built-in>:361:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
1 warning generated.
In file included from <built-in>:368:
<command line>:3:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 21
        ^
<built-in>:361:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
1 warning generated.
In file included from <built-in>:368:
<command line>:3:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 21
        ^
<built-in>:361:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
1 warning generated.
In file included from <built-in>:368:
<command line>:3:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 21
        ^
<built-in>:361:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
1 warning generated.
In file included from <built-in>:368:
<command line>:3:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 21
        ^
<built-in>:361:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
1 warning generated.
In file included from <built-in>:368:
<command line>:3:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 21
        ^
<built-in>:361:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^

**Comment by ivk1800** [comment]
I am do not use local machine for build tdlib, please check [github action script](https://github.com/ivk1800/td-json-client-prebuilt/blob/master/.github/workflows/build-tdlib.yml)
It is best to contact this question at https://github.com/tdlib/td/issues/77

**Comment by JrAnTran** [comment]
> I am do not use local machine for build tdlib, please check [github action script](https://github.com/ivk1800/td-json-client-prebuilt/blob/master/.github/workflows/build-tdlib.yml) It is best to contact this question at [tdlib/td#77](https://github.com/tdlib/td/issues/77)

I run the libs created above normally, so I think it's trivial.Close it now
@ivk1800
